version: '3.8'

services:
    web:
        container_name: web
        image: web
        build:
            context: ./web
        ports:
            - 3000:3000

    api:
        container_name: api
        image: api
        build:
            context: ./api
        ports:
            - 5000:5000